// Static JSON endpoint serving the machine-readable directory data.
// Mirrors data/exports/entries.json, regenerated by CI on every push.
import { readFileSync } from "node:fs";
import path from "node:path";

const EXPORT_PATH = path.resolve("../data/exports/entries.json");
const data = JSON.parse(readFileSync(EXPORT_PATH, "utf8"));

export async function GET() {
  return new Response(JSON.stringify(data, null, 2), {
    headers: {
      "Content-Type": "application/json; charset=utf-8",
      "Access-Control-Allow-Origin": "*",
    },
  });
}
